### ISSUE TITLE
Prepare report for meeting

### ISSUE THREAD

**Issue by halasadi** [halasadi/ancient-structure#12]
We need to provide a summary of our progress to Matthew. We plan to present the following:

(1) What is the problem we are tackling? What have previous studies done and what are their flaws.

(2) Exploratory data analysis on the data : PCA and general Admixture 

(3) (a) Talk about the basic model without sampling correction. We simulated under the WF model. Show the drift factor and how it's not a problem. (b) Show him how finite sample size can introduce a lot of error.  (c) Show the real data analysis.

(4) We've developed a modification and show him the doc that we've prepared.

(5) (a) Under the new model, show results under simulations with and without drift. (b) Furthermore, apply the new model on real data.

(6) Main conclusions: We provide an alternate analysis to analyze ancient DNA. Our analysis shows that moderns cannot be written as a mixture of three source frequencies as claimed by Haak et al. 

Discussion: drift and contamination.

**Comment by kkdey** [comment]
1. What is the problem we are tackling? What have previous studies done and what are their flaws

See :  https://github.com/halasadi/ancient-structure/blob/master/docs/Matthew%20report/introduction.pdf

2. Exploratory data analysis on the data : PCA and general Admixture 

See : https://github.com/halasadi/ancient-structure/blob/master/docs/Matthew%20report/plot_exploratory.pdf

3. Talk about the basic model without sampling correction. We simulated under the WF model. Show the drift factor and how it's not a problem. Show how finite sample size can introduce a lot of error.

See :
