### ISSUE TITLE
Check the data quality Haak et al 2015

### ISSUE THREAD

**Issue by halasadi** [halasadi/ancient-structure#14]
We need to check that the data-set posted by David Reich's group is already cleaned. So far, we know that they performed a LD filtering step but beyond that, we are not sure if there other steps taken by Haak et al to filter the data before applying ADMIXTURE. To make sure, we should try to replicate their results. Furthermore, talking to Cheongwong or John Lindo will be helpful to make sure we are treating the data correctly.

**Comment by kkdey** [comment]
The dataset used to apply admixture in the Haak et al paper is the same as the one we were using except for the LD pruning which we have corrected for.
